### ISSUE TITLE
Web documentation missing, though it is referenced

### ISSUE THREAD

**Issue by niftylettuce** [slackhq/node-slack-sdk#215] opened 2016-05-20 16:30 UTC
You reference a web documentation API here and the ability to use it with this package, but you fail to mention how.  Only RTM is mentioned.

**Comment by ekmartin** [comment] 2016-05-20 16:31
#193

**Comment by DEGoodmanWilson** [comment] 2016-06-06 18:13
Closing as a duplicate of #193

**Closed by DEGoodmanWilson** 2016-06-06 18:13 UTC
Labels: docs, duplicate
